import '@/styles/globals.css'
import type { ReactNode } from 'react'
import { openSans } from '@/utils/font'
import AsideArea from '@/components/AsideArea'
import AsideCategory from '@/components/AsideCategory'
import AsideSearch from '@/components/AsideSearch'
import AsideUpdatedSpot from '@/components/AsideUpdatedSpot'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja" className={openSans.variable}>
      <body className="font-body font-light text-black md:text-gray-800">
        <Header />

        <div className="m-auto w-full max-w-7xl px-4 py-10">
          <div className="flex flex-col justify-between gap-12 lg:flex-row">
            <main className="w-full max-w-full pb-0 leading-relaxed lg:max-w-[820px] lg:pb-20">
              {children}
            </main>
            <aside className="w-full shrink-0 lg:w-[300px]">
              <AsideSearch />
              <AsideUpdatedSpot />
              <AsideArea />
              <AsideCategory />
            </aside>
          </div>
        </div>

        <Footer />
      </body>
    </html>
  )
}
