import { AsideArea } from '@/components/layouts/AsideArea'
import { AsideCategory } from '@/components/layouts/AsideCategory'
import { AsideUpdatedSpots } from '@/components/layouts/AsideUpdatedSpots'
import { Footer } from '@/components/layouts/Footer'
import { Header } from '@/components/layouts/Header'
import { Input } from '@/components/ui/input'
import '@/styles/globals.css'
import { inter } from '@/utils/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={inter.variable} lang="ja">
      <body className="font-body text-black md:text-gray-800">
        <Header />

        <div className="m-auto w-full max-w-7xl px-4 py-10">
          <div className="flex flex-col justify-between gap-12 lg:flex-row">
            <main className="w-full max-w-full pb-0 leading-relaxed lg:max-w-[820px] lg:pb-20">
              {children}
            </main>

            <aside className="w-full shrink-0 lg:w-[300px]">
              <div className="mb-12">
                <Input
                  className="text-base"
                  placeholder="サイト内検索"
                  type="text"
                />
              </div>

              <AsideUpdatedSpots />
              <AsideArea />
              <AsideCategory />
            </aside>
          </div>
        </div>

        <Footer />
      </body>
    </html>
  )
}
