import { Heading } from '@/components/elements/Heading'
import { Link } from '@/components/elements/Link'
import { Footer } from '@/components/layouts/Footer'
import { Header } from '@/components/layouts/Header'
import { Input } from '@/components/ui/input'
import '@/styles/globals.css'
import { inter } from '@/utils/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={inter.variable} lang="ja">
      <body className="font-body text-black md:text-gray-800">
        <Header />

        <div className="m-auto w-full max-w-7xl px-4 py-10">
          <div className="flex flex-col justify-between gap-12 lg:flex-row">
            <main className="w-full max-w-full pb-0 leading-relaxed lg:max-w-[820px] lg:pb-20">
              {children}
            </main>

            <aside className="w-full shrink-0 lg:w-[300px]">
              <div className="mb-12">
                <Input
                  className="text-base"
                  placeholder="サイト内検索"
                  type="text"
                />
              </div>

              <div className="mb-12">
                <Heading.Basic>最近更新されたスポット</Heading.Basic>
                <ul>
                  <li className="border-b border-gray-200">
                    <a className="block px-2 py-3 hover:underline" href="#">
                      大力餅 衣笠店
                    </a>
                  </li>
                  <li className="border-b border-gray-200">
                    <a className="block px-2 py-3 hover:underline" href="#">
                      赤垣屋
                    </a>
                  </li>
                  <li className="border-b border-gray-200">
                    <a className="block px-2 py-3 hover:underline" href="#">
                      とんかつ豚ゴリラ 本店（円町）
                    </a>
                  </li>
                  <li className="border-b border-gray-200">
                    <a className="block px-2 py-3 hover:underline" href="#">
                      焼肉ホルモン まもすけ
                    </a>
                  </li>
                  <li className="border-b border-gray-200">
                    <a className="block px-2 py-3 hover:underline" href="#">
                      とくら 京都三条店
                    </a>
                  </li>
                  <li className="border-b border-gray-200">
                    <a className="block px-2 py-3 hover:underline" href="#">
                      銀閣寺喜み家
                    </a>
                  </li>
                </ul>
              </div>

              <div className="mb-12">
                <Heading.Basic>エリア</Heading.Basic>
                <ul className="flex flex-wrap gap-2">
                  <li>
                    <Link.Basic href="#">四条烏丸</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">河原町</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">御所周辺</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">二条城</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">祇園・東山・清水</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">岡崎・吉田</Link.Basic>
                  </li>
                </ul>
              </div>

              <div className="mb-12">
                <Heading.Basic>カテゴリ</Heading.Basic>
                <ul className="flex flex-wrap gap-2">
                  <li>
                    <Link.Basic href="#">とんかつ</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">うどん・そば・定食</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">焼肉・ステーキ・肉バル</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">居酒屋・割烹</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">ラーメン</Link.Basic>
                  </li>
                  <li>
                    <Link.Basic href="#">寿司・うなぎ・天ぷら</Link.Basic>
                  </li>
                </ul>
              </div>
            </aside>
          </div>
        </div>

        <Footer />
      </body>
    </html>
  )
}
